language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  global:
  - DEPS="pandas pytest traitlets ipython pytest"

  matrix:
  - BUILD_TYPE="test"

matrix:
  include:
  - python: 3.5
    env: BUILD_TYPE="docs"

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $DEPS
  - python setup.py install

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - if [[ $BUILD_TYPE == 'docs' ]]; then
       sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++;
    fi

script:
  - if [[ $BUILD_TYPE == 'test' ]]; then
       py.test altair --doctest-modules;
    elif [[ $BUILD_TYPE == 'docs' ]]; then
       bash ./build_docs.sh;
    fi
