name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: black-flake8-mypy
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Check formatting with black
      run: |
        pip install "black<24"
        black --diff --color .
        black --check .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .  --statistics
    - name: Lint with mypy
      run: |
        pip install mypy pandas-stubs types-jsonschema types-setuptools
        mypy altair tests
